package com.fwd.salesInvoiceSystem.View;



public class NewInvoicePanel extends javax.swing.JPanel {

    /**
     * Creates new form InvoicePanel
     */
    public NewInvoicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        invoiceNoLabel = new javax.swing.JLabel();
        invoiceDateLabel = new javax.swing.JLabel();
        custNameLabel = new javax.swing.JLabel();
        custNameValue = new javax.swing.JTextField();
        invoiceNoValue = new javax.swing.JFormattedTextField();
        invoiceDateValue = new javax.swing.JFormattedTextField();

        invoiceNoLabel.setText("No :");

        invoiceDateLabel.setText("Date :");

        custNameLabel.setText("Customer Name :");
        invoiceNoValue.setEditable(false);
        invoiceNoValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        invoiceDateValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(custNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(invoiceNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(invoiceDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(custNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(invoiceNoValue)
                                        .addComponent(invoiceDateValue))
                                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(invoiceNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(invoiceNoValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(invoiceDateLabel)
                                        .addComponent(invoiceDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(custNameLabel)
                                        .addComponent(custNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>

    public String getInvoiceDateValue() {
        return invoiceDateValue.getText();
    }

    public String getCustNameValue() {
        return custNameValue.getText();
    }

    public String getInvoiceNoValue() {
        return invoiceNoValue.getText();
    }

    public void setInvoiceNoValue(String invoiceNoValue) {
        this.invoiceNoValue.setText(invoiceNoValue);
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel custNameLabel;
    private javax.swing.JTextField custNameValue;
    private javax.swing.JLabel invoiceDateLabel;
    private javax.swing.JFormattedTextField invoiceDateValue;
    private javax.swing.JLabel invoiceNoLabel;
    private javax.swing.JFormattedTextField invoiceNoValue;
    // End of variables declaration
}

